
services: 
  # Serveur MCP unifié principal
  unified-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: unified-mcp-server
    restart: unless-stopped
    env_file:
      - path: .env
        required: false # Makes the file optional
    ports:
      - "3003:3000"  # Port principal pour l'API proxy
      - "3004:3001"  # Port SSE
    volumes:
      - ./workspace:/workspace:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro  # Pour github-mcp-server
    environment:
      - GITHUB_PAT=${GITHUB_PAT:-}
      - MCP_HOST=0.0.0.0
      - MCP_PORT=3000
      - MCP_SSE_PORT=3001
      - NODE_ENV=production
      - PYTHONUNBUFFERED=1
      # Configuration pour les modèles VLLM
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT:-https://kitty.guidry-cloud.com/v1}
      - MODEL_NAME=${MODEL_NAME:-kitten-kitkat/Qwen3-4B-Thinking-2507}
      - SMALL_MODEL_NAME=${SMALL_MODEL_NAME:-kitten-kitkat/Qwen3-4B-Thinking-2507}
      - EMBEDDER_MODEL_NAME=${EMBEDDER_MODEL_NAME:-sentence-transformers/all-MiniLM-L6-v2}
    networks:
      - mcp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - docker-dind
    privileged: false
    security_opt:
      - no-new-privileges:true
    user: "node"

  # Service Docker-in-Docker pour les serveurs MCP qui nécessitent Docker
  docker-dind:
    image: docker:24-dind
    container_name: unified-mcp-docker
    restart: unless-stopped
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - docker-certs-ca:/certs/ca
      - docker-certs-client:/certs/client
      - ./workspace:/workspace:rw
    networks:
      - mcp-network
    command: ["dockerd", "--host=unix:///var/run/docker.sock", "--host=tcp://0.0.0.0:2376", "--tls=false"]

  # VS Code Server (Dev Container)
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: unified-code-server
    env_file:
      - path: .env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD=${CODE_SERVER_PASSWORD:-password} # fallback if not set
      # - HASHED_PASSWORD= # optional (use if you want a pre-hashed password)
      - SUDO_PASSWORD=${CODE_SERVER_ADMIN:-kittenity} # optional
      #- SUDO_PASSWORD_HASH=   # optional
      - PROXY_DOMAIN=code.guidry-cloud.com # optional (reverse proxy domain)
      - DEFAULT_WORKSPACE=/workspace
      - PWA_APPNAME=Unified VS Code
    volumes:
      - ./workspace:/workspace:rw         # your shared project workspace
      - /var/run/docker.sock:/var/run/docker.sock # optional: docker access inside VS Code
    ports:
      - "8449:8443"
    networks:
      - mcp-network
    restart: unless-stopped

networks:
  mcp-network:
    driver: bridge
    name: mcp-unified-network

volumes:
  neo4j_data:
    name: mcp-neo4j-data
  neo4j_logs:
    name: mcp-neo4j-logs
  docker-certs-ca:
    name: mcp-docker-certs-ca
  docker-certs-client:
    name: mcp-docker-certs-client

